/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './tags/tag.component.ngfactory';
import * as i2 from './tags/tag.component';
import * as i3 from './stock.service';
import * as i4 from '@angular/forms';
import * as i5 from './stock.component';
import * as i6 from '@angular/common';
import * as i7 from './chart/chart.component.ngfactory';
import * as i8 from './chart/chart.component';
const styles_StockComponent:any[] = [''];
export const RenderType_StockComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_StockComponent,data:{}});
function View_StockComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-tag',([] as any[]),
      (null as any),(null as any),(null as any),i1.View_TagComponent_0,i1.RenderType_TagComponent)),
      i0.ɵdid(49152,(null as any),0,i2.TagComponent,[i3.StockService],{stock:[0,'stock']},
          (null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_StockComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),10,'form',[['class',''],['novalidate','']],[[2,'ng-untouched',
          (null as any)],[2,'ng-touched',(null as any)],[2,'ng-pristine',(null as any)],
          [2,'ng-dirty',(null as any)],[2,'ng-valid',(null as any)],[2,'ng-invalid',
              (null as any)],[2,'ng-pending',(null as any)]],[[(null as any),'submit'],
          [(null as any),'reset']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('submit' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,3).onSubmit($event)) !== false);
          ad = (pd_0 && ad);
        }
        if (('reset' === en)) {
          const pd_1:any = ((<any>i0.ɵnov(_v,3).onReset()) !== false);
          ad = (pd_1 && ad);
        }
        return ad;
      },(null as any),(null as any))),i0.ɵdid(16384,(null as any),0,i4.ɵbf,([] as any[]),
      (null as any),(null as any)),i0.ɵdid(16384,(null as any),0,i4.NgForm,[[8,(null as any)],
      [8,(null as any)]],(null as any),(null as any)),i0.ɵprd(2048,(null as any),i4.ControlContainer,
      (null as any),[i4.NgForm]),i0.ɵdid(16384,(null as any),0,i4.NgControlStatusGroup,
      [i4.ControlContainer],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
      ['\n  '])),(_l()(),i0.ɵeld(0,[['f',1]],(null as any),0,'input',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      1,'button',([] as any[]),(null as any),[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i5.StockComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.getaStock(i0.ɵnov(_v,7).value)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Hit me!'])),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),['\n'])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class','col-md-4']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_StockComponent_1)),i0.ɵdid(802816,(null as any),
          0,i6.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,
              'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),
          i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'app-chart',([] as any[]),(null as any),(null as any),(null as any),i7.View_ChartyComponent_0,
          i7.RenderType_ChartyComponent)),i0.ɵdid(114688,(null as any),0,i8.ChartyComponent,
          [i3.StockService],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i5.StockComponent = _v.component;
    const currVal_7:any = _co.stocks;
    _ck(_v,16,0,currVal_7);
    _ck(_v,20,0);
  },(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,5).ngClassUntouched;
    const currVal_1:any = i0.ɵnov(_v,5).ngClassTouched;
    const currVal_2:any = i0.ɵnov(_v,5).ngClassPristine;
    const currVal_3:any = i0.ɵnov(_v,5).ngClassDirty;
    const currVal_4:any = i0.ɵnov(_v,5).ngClassValid;
    const currVal_5:any = i0.ɵnov(_v,5).ngClassInvalid;
    const currVal_6:any = i0.ɵnov(_v,5).ngClassPending;
    _ck(_v,1,0,currVal_0,currVal_1,currVal_2,currVal_3,currVal_4,currVal_5,currVal_6);
  });
}
export function View_StockComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-stock',([] as any[]),
      (null as any),(null as any),(null as any),View_StockComponent_0,RenderType_StockComponent)),
      i0.ɵdid(114688,(null as any),0,i5.StockComponent,[i3.StockService],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const StockComponentNgFactory:i0.ComponentFactory<i5.StockComponent> = i0.ɵccf('app-stock',
    i5.StockComponent,View_StockComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvU3RvY2tfYXBwL2Fzc2V0cy9hcHAvc3RvY2tzL3N0b2NrLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9uZ3Roby9Eb2N1bWVudHMvSmF2YVNjcmlwdC9TdG9ja19hcHAvYXNzZXRzL2FwcC9zdG9ja3Mvc3RvY2suY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvU3RvY2tfYXBwL2Fzc2V0cy9hcHAvc3RvY2tzL3N0b2NrLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvU3RvY2tfYXBwL2Fzc2V0cy9hcHAvc3RvY2tzL3N0b2NrLmNvbXBvbmVudC50cy5TdG9ja0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxyXG48Zm9ybSBjbGFzcz1cIlwiPlxyXG4gIDxpbnB1dCAjZj5cclxuICA8YnV0dG9uIChjbGljayk9XCJnZXRhU3RvY2soZi52YWx1ZSlcIj5IaXQgbWUhPC9idXR0b24+XHJcbjwvZm9ybT5cclxuPGRpdiBjbGFzcz0nY29sLW1kLTQnPlxyXG4gICAgPGFwcC10YWdcclxuICAgICpuZ0Zvcj1cImxldCBzdG9jayBvZiBzdG9ja3NcIlxyXG4gICAgW3N0b2NrXT1cInN0b2NrXCJcclxuICAgID48L2FwcC10YWc+XHJcbjwvZGl2PlxyXG48YXBwLWNoYXJ0PjwvYXBwLWNoYXJ0PlxyXG4iLCI8YXBwLXN0b2NrPjwvYXBwLXN0b2NrPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNNSTtNQUFBO2FBQUE7VUFBQTtJQUVBO0lBRkEsV0FFQSxTQUZBOzs7O29CQU5KLHVDQUNBO01BQUE7VUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7VUFBQTtVQUFBO1FBQUE7UUFBQTtVQUFBO1VBQUE7UUFBQTtRQUFBO01BQUEsdUNBQUE7TUFBQSxvQ0FBQTtNQUFBLHVEQUFBO01BQUEsa0NBQUE7TUFBQSxtREFBZTtNQUFBLFdBQ2I7TUFBQSx3RUFBVTthQUFBLDBCQUNWO01BQUE7UUFBQTtRQUFBO1FBQVE7VUFBQTtVQUFBO1FBQUE7UUFBUjtNQUFBLGdDQUFxQztNQUFnQix1Q0FDaEQ7TUFDUDtVQUFBO01BQXNCLDJDQUNsQjtVQUFBLDZEQUFBO1VBQUE7Y0FBQSwyQkFHVyx1Q0FDVDtpQkFBQSx3QkFDTjtVQUFBO3VDQUFBLFVBQUE7VUFBQSwrQ0FBdUI7VUFBQTs7SUFKbkI7SUFEQSxZQUNBLFNBREE7SUFLSjs7SUFWQTtJQUFBO0lBQUE7SUFBQTtJQUFBO0lBQUE7SUFBQTtJQUFBLFdBQUEscUVBQUE7Ozs7b0JDREE7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
