/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './header.component';
const styles_HeaderComponent:any[] = ['.navbar[_ngcontent-%COMP%] {\n      height: 60px;\n    }\n    .navbar-brand[_ngcontent-%COMP%] {\n      padding: 19px 15px;\n      font-size: 1.8em;\n    }\n    a[_ngcontent-%COMP%] {\n      cursor: pointer;\n    }'];
export const RenderType_HeaderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_HeaderComponent,data:{}});
export function View_HeaderComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),10,'nav',[['class','navbar navbar-inverse']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),7,'div',[['class','container-fluid']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n      '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),4,'div',[['class','navbar-header']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a',[['class',
          'navbar-brand'],['routerLink','/']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['StockView'])),
      (_l()(),i0.ɵted((null as any),['\n      '])),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵted((null as any),['\n\n  ']))],
      (null as any),(null as any));
}
export function View_HeaderComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),
      (null as any),(null as any),(null as any),View_HeaderComponent_0,RenderType_HeaderComponent)),
      i0.ɵdid(49152,(null as any),0,i1.HeaderComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const HeaderComponentNgFactory:i0.ComponentFactory<i1.HeaderComponent> = i0.ɵccf('app-header',
    i1.HeaderComponent,View_HeaderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvU3RvY2tfYXBwL2Fzc2V0cy9hcHAvaGVhZGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9uZ3Roby9Eb2N1bWVudHMvSmF2YVNjcmlwdC9TdG9ja19hcHAvYXNzZXRzL2FwcC9oZWFkZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvU3RvY2tfYXBwL2Fzc2V0cy9hcHAvaGVhZGVyLmNvbXBvbmVudC50cy5IZWFkZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL25ndGhvL0RvY3VtZW50cy9KYXZhU2NyaXB0L1N0b2NrX2FwcC9hc3NldHMvYXBwL2hlYWRlci5jb21wb25lbnQudHMuSGVhZGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gIDxuYXYgY2xhc3M9XCJuYXZiYXIgbmF2YmFyLWludmVyc2VcIj5cbiAgICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyLWZsdWlkXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwibmF2YmFyLWhlYWRlclwiPlxuICAgICAgICA8YSByb3V0ZXJMaW5rPScvJyBjbGFzcz1cIm5hdmJhci1icmFuZFwiPlN0b2NrVmlldzwvYT5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L25hdj5cblxuICAiLCI8YXBwLWhlYWRlcj48L2FwcC1oZWFkZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUEseUNBQ0U7TUFBQTtNQUFBLDRDQUFtQztNQUNqQztVQUFBO01BQTZCLDZDQUMzQjtVQUFBO1VBQUEsNENBQTJCO1VBQUEsaUJBQ3pCO1VBQUE7VUFBQSw4QkFBdUM7TUFBYSw2Q0FDaEQ7TUFDRix5Q0FDRjs7OztvQkNQUjtNQUFBO2FBQUE7VUFBQTs7OyJ9
