/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.box[_ngcontent-%COMP%] {\r\n  box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 6px, rgba(0, 0, 0, 0.12) 0px 1px 4px;\r\n  min-width: 190px;\r\n  padding: 0px;\r\n  margin: 15px;\r\n}\r\n\r\n#head[_ngcontent-%COMP%] {\r\n  display: inline-block;\r\n  width: 100%;\r\n  background-color: #e7e7e7;\r\n  float: left;\r\n\r\n}\r\n#head[_ngcontent-%COMP%]   h2[_ngcontent-%COMP%] {\r\n  margin: 6px 6px;\r\n  float: left;\r\n}\r\n\r\nspan[_ngcontent-%COMP%] {\r\n  float: left;\r\n  margin: 20px 10px;\r\n\r\n}\r\n[class*=\'close-\'][_ngcontent-%COMP%] {\r\n  color: #777;\r\n  font-size: 1.1em;\r\n  font: 14px/100% arial, sans-serif;\r\n  position: absolute;\r\n  right: 7px;\r\n  text-decoration: none;\r\n  text-shadow: 0 1px 0 #fff;\r\n  top: 7px;\r\n}\r\n\r\n.close-thik[_ngcontent-%COMP%]:after {\r\n  content: \'✖\'; \r\n  font-size: 1.37em;\r\n  font-weight: bold;\r\n  cursor: pointer;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvU3RvY2tfYXBwL2Fzc2V0cy9hcHAvc3RvY2tzL3RhZ3MvdGFnLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvU3RvY2tfYXBwL2Fzc2V0cy9hcHAvc3RvY2tzL3RhZ3MvdGFnLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
